# child device template
x-child-defaults: &child-defaults
  image: ghcr.io/thin-edge/tedge-demo-child:${VERSION:-latest}
  pull_policy: always
  restart: always
  networks:
    - tedge

# Services
services:
  tedge:
    image: ghcr.io/thin-edge/tedge-demo-main-systemd:${VERSION:-latest}
    pull_policy: always
    volumes:
      - etc:/etc
      # Enable docker from docker - But then this container has elevated access to system resources!
      - /var/run/docker.sock:${DOCKER_SOCKET:-/var/run/docker.sock}:rw
    restart: always
    tmpfs:
      - /run
      - /tmp
    privileged: true
    environment:
      - DEVICE_ID=${DEVICE_ID:-}
      - C8Y_BASEURL=${C8Y_BASEURL:-}
      - C8Y_USER=${C8Y_USER:-}
    networks:
      - tedge

  # child devices
  child01:
    <<: *child-defaults
    environment:
      - CONNECTOR_DEVICE_ID=child01

  child02:
    <<: *child-defaults
    environment:
      - CONNECTOR_DEVICE_ID=child02

volumes:
  etc:

networks:
  tedge:
