version: '3'

# child device template
x-child-defaults: &child-defaults
  build:
      context: "../child-device"
      dockerfile: child.dockerfile
  restart: always
  networks:
    - tedge

services:
  tedge:
    build:
      context: ".."
      dockerfile: debian-systemd/debian-systemd.dockerfile
    environment:
      - DEVICE_ID=${DEVICE_ID:-}
      - C8Y_BASEURL=${C8Y_BASEURL:-}
      - C8Y_USER=${C8Y_USER:-}
    volumes:
      - etc:/etc

      # Enable docker from docker - But then this container has elevated access to system resources!
      - /var/run/docker.sock:${DOCKER_SOCKET:-/var/run/docker.sock}:rw

    restart: always
    privileged: true
    networks:
      - tedge

  # child devices
  child01:
    <<: *child-defaults
    environment:
      - CONNECTOR_DEVICE_ID=child01

  child02:
    <<: *child-defaults
    environment:
      - CONNECTOR_DEVICE_ID=child02

volumes:
  etc:

networks:
  tedge:
