# child device templates
x-child-agent: &child-container
  build:
      context: ".."
      dockerfile: child-device-container/child.dockerfile
  restart: always
  tmpfs:
    - /tmp
  networks:
    - tedge

x-child-defaults: &child-device-systemd
  build:
      context: ".."
      dockerfile: child-device-systemd/child.dockerfile
  restart: always
  privileged: true
  networks:
    - tedge

services:
  tedge:
    build:
      context: ".."
      dockerfile: debian-systemd/debian-systemd.dockerfile
    environment:
      - DEVICE_ID=${DEVICE_ID:-}
      - C8Y_BASEURL=${C8Y_BASEURL:-}
      - C8Y_USER=${C8Y_USER:-}
      - FEATURES=${FEATURES:-pki}
      - PROVISION_PASSWORD=${PROVISION_PASSWORD:-dummy}
    volumes:
      - etc:/etc

    restart: always
    privileged: true
    hostname: tedge
    networks:
      - tedge

  # child devices
  child01:
    <<: *child-container
    environment:
      - FEATURES=${FEATURES:-pki}
      - PROVISION_PASSWORD=${PROVISION_PASSWORD:-dummy}
    hostname: child01
    volumes:
      - child01_etc:/etc
      - child01_logs:/var/log/tedge

  child02:
    <<: *child-device-systemd
    hostname: child02
    environment:
      - FEATURES=${FEATURES:-pki}
      - PROVISION_PASSWORD=${PROVISION_PASSWORD:-dummy}
    volumes:
      - child02_etc:/etc
      - child02_logs:/var/log/tedge

volumes:
  etc:
  child01_etc:
  child01_logs:
  child02_etc:
  child02_logs:

networks:
  tedge:
