version: "3"

# device template
x-device-defaults: &device-defaults
  build:
    dockerfile: alpine-s6.dockerfile
    context: "."
  restart: always
  tmpfs:
    - /tmp
  # Support reaching other services from the host, e.g. curl http://host.docker.internal:8888
  extra_hosts:
    - "host.docker.internal:host-gateway"
  networks:
    - tedge
  depends_on:
    - mosquitto

x-device-env: &device-env
    TEDGE_MQTT_CLIENT_HOST: mosquitto
    #
    # Enable/disable specific services
    #
    REGISTER_DEVICE: 1
    SERVICE_TEDGE_AGENT: 1
    SERVICE_TEDGE_CONFIGURATION_PLUGIN: 1
    SERVICE_TEDGE_LOG_PLUGIN: 1
    SERVICE_TEDGE_MAPPER_C8Y: 0
    SERVICE_TEDGE_MAPPER_AZ: 0
    SERVICE_TEDGE_MAPPER_AWS: 0
    SERVICE_TEDGE_MAPPER_COLLECTD: 0
    SERVICE_C8Y_FIRMWARE_PLUGIN: 0
    SERVICE_MOSQUITTO: 0

services:
  mosquitto:
    build:
      dockerfile: mosquitto/mosquitto.dockerfile
      context: "."
    restart: always
    environment:
      - TEDGE_C8Y_URL=${C8Y_DOMAIN:-}
      - C8Y_USER=${C8Y_USER:-}
      - C8Y_PASSWORD=${C8Y_PASSWORD:-}
      - DEVICE_ID=${DEVICE_ID:-}
    volumes:
      - device-certs:/etc/tedge/device-certs
      - mosquitto:/mosquitto/data
    networks:
      - tedge

  tedge-mapper-c8y:
    build:
      dockerfile: alpine-s6.dockerfile
      context: "."
    restart: always
    environment:
      - TEDGE_MQTT_CLIENT_HOST=mosquitto
      - TEDGE_HTTP_CLIENT_HOST=tedge
      - TEDGE_C8Y_URL=${C8Y_DOMAIN:-}
      #
      # Enable/disable specific services
      #
      - SERVICE_TEDGE_MAPPER_C8Y=1
      # FIXME: remove once c8y-firmware-plugin has been made generic
      # Run c8y-firmware-plugin on the mapper as it needs access to the certificates and c8y.url
      - SERVICE_C8Y_FIRMWARE_PLUGIN=1
      - SERVICE_TEDGE_AGENT=0
      - SERVICE_TEDGE_CONFIGURATION_PLUGIN=0
      - SERVICE_TEDGE_LOG_PLUGIN=0
      - SERVICE_TEDGE_MAPPER_AZ=0
      - SERVICE_TEDGE_MAPPER_AWS=0
      - SERVICE_TEDGE_MAPPER_COLLECTD=0
      - SERVICE_MOSQUITTO=0
    volumes:
      - device-certs:/etc/tedge/device-certs
      # FIXME: Remove volume once https://github.com/thin-edge/thin-edge.io/issues/2390 is resolved
      - file-transfer:/var/tedge
    tmpfs:
      - /tmp
    # Support reaching other services from the host, e.g. curl http://host.docker.internal:8888
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - tedge
    depends_on:
      - mosquitto
    # FIXME: Remove volume once https://github.com/thin-edge/thin-edge.io/issues/2390 is resolved
    # However this is only required if the tedge container is running under the root user
    user: root

  # main device
  tedge:
    <<: *device-defaults
    environment:
      <<: *device-env
      TEDGE_MQTT_DEVICE_TOPIC_ID: device/main//

    # FIXME: Remove volume once https://github.com/thin-edge/thin-edge.io/issues/2390 is resolved
    volumes:
      - file-transfer:/var/tedge
    user: root

  # child devices
  child01:
    <<: *device-defaults
    environment:
      <<: *device-env
      TEDGE_MQTT_DEVICE_TOPIC_ID: device/child01//
    user: root

volumes:
  device-certs:
  mosquitto:
  file-transfer:

networks:
  tedge:
