version: "3"
services:
  tedge:
    build:
      dockerfile: alpine-s6.dockerfile
      context: "."
    restart: always
    # ports:
    #   - "1883:1883"
    environment:
      - DEVICE_ID=${DEVICE_ID:-}
      - TEDGE_C8Y_URL=${C8Y_DOMAIN:-}
      - C8Y_USER=${C8Y_USER:-}
      - C8Y_PASSWORD=${C8Y_PASSWORD:-}
      # PKI which is hosted on the user's host machine
      - CFSSL_HOST=host.docker.internal:8888
      - USE_PKI=1
      - PKI_PROVIDER=pki-cfssl
    volumes:
      - mosquitto:/mosquitto/data
      - device-certs:/etc/tedge/device-certs
    tmpfs:
      - /tmp

    # Support reaching other services from the host, e.g. curl http://host.docker.internal:8888
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  device-certs:
  mosquitto:
