[[files]]
path = '/etc/tedge/tedge.toml'
type = 'tedge.toml'
user = 'tedge'
group = 'tedge'
mode = 0o444

[[files]]
path = '/etc/tedge/plugins/tedge-log-plugin.toml'
type = 'tedge-log-plugin'
user = 'tedge'
group = 'tedge'
mode = 0o644

[[files]]
path = '/etc/tedge/system.toml'
type = 'system.toml'
user = 'tedge'
group = 'tedge'
mode = 0o444

[[files]]
path = '/etc/mosquitto/conf.d/mosquitto.conf'
type = 'mosquitto.conf'
user = 'root'
group = 'root'
mode = 0o644

[[files]]
path = '/etc/collectd/collectd.conf'
type = 'collectd.conf'
user = 'root'
group = 'root'
mode = 0o644

[[files]]
path = '/etc/tedge-command-plugin/env'
type = 'shell'
user = 'tedge'
group = 'tedge'
mode = 0o644
