version: "3"

# device template
x-device-defaults: &defaults
  build:
    dockerfile: alpine.dockerfile
    context: "."
  restart: always
  tmpfs:
    - /tmp
  # Support reaching other services from the host, e.g. curl http://host.docker.internal:8888
  extra_hosts:
    - "host.docker.internal:host-gateway"
  networks:
    - tedge
  depends_on:
    - mosquitto
  # Not recommended: Use root if you want to be able to install apk packages within the container at runtime
  # otherwise just use tedge which is a non-root user.
  user: root


services:
  mosquitto:
    image: ghcr.io/thin-edge/tedge-mosquitto:${VERSION:-latest}
    restart: always
    environment:
      - TEDGE_C8Y_URL=${C8Y_DOMAIN:-}
      - C8Y_USER=${C8Y_USER:-}
      - C8Y_PASSWORD=${C8Y_PASSWORD:-}
      - DEVICE_ID=${DEVICE_ID:-}
    volumes:
      - mosquitto:/mosquitto/data
      - device-certs:/etc/tedge/device-certs
    networks:
      - tedge

  tedge-mapper-c8y:
    <<: *defaults
    command: ["/usr/bin/tedge-mapper", "c8y"]
    environment:
      - TEDGE_C8Y_URL=${C8Y_DOMAIN:-}
    volumes:
      - device-certs:/etc/tedge/device-certs

  # FIXME: Remove once the following ticket is resolved and there is child operation supervision
  # * https://github.com/thin-edge/thin-edge.io/issues/2453
  c8y-firmware-plugin:
    <<: *defaults
    command: ["/usr/bin/c8y-firmware-plugin"]
    environment:
      - TEDGE_C8Y_URL=${C8Y_DOMAIN:-}
    volumes:
      - device-certs:/etc/tedge/device-certs

  # main device
  tedge:
    <<: *defaults
    command: ["/usr/bin/tedge-agent-v1", "--mqtt-device-topic-id", "device/main//"]

  # child devices
  child01:
    <<: *defaults
    command: ["/usr/bin/tedge-agent-v1", "--mqtt-device-topic-id", "device/child01//"]

volumes:
  device-certs:
  mosquitto:
  file-transfer:

networks:
  tedge:
