name: Test

on:
  workflow_dispatch:
  # Use a manual approval process before PR's are given access to
  # the secrets which are required to run the integration tests.
  # The PR code should be manually approved to see if it can be trusted.
  # When in doubt, do not approve the test run.
  # Reference: https://dev.to/petrsvihlik/using-environment-protection-rules-to-secure-secrets-when-building-external-forks-with-pullrequesttarget-hci
  pull_request_target:
    branches: [ main ]
  push:
    branches: [ main ]
  merge_group:
jobs:
  test:
    name: Test ${{ matrix.job.target }}
    environment:
      # For security reasons, all pull requests need to be approved first before granting access to secrets
      # So the environment should be set to have a reviewer/s inspect it before approving it
      name: ${{ github.event_name == 'pull_request_target' && 'Test Pull Request' || 'Test Auto'  }}
    runs-on: ubuntu-20.04
    env:
      COMPOSE_PROJECT_NAME: ci_${{ matrix.job.target }}_${{github.run_id}}_${{github.run_attempt || '1'}}
      DEVICE_ID: ci_${{ matrix.job.target }}_${{github.run_id}}_${{github.run_attempt || '1'}}

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        job:
          - { target: debian-systemd, bootstrap: true }
          - { target: alpine-s6, bootstrap: false }

    steps:
      # Checkout either the PR or the branch
      - name: Checkout PR
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }} # Check out the code of the PR. Only after the manual approval process

      - name: Checkout
        uses: actions/checkout@v3
        if: ${{ github.event_name != 'pull_request_target' }}

      - name: create .env file
        run: |
          touch .env
          echo "DEVICE_ID=$DEVICE_ID" >> .env
          C8Y_DOMAIN=$(echo "${{ secrets.C8Y_BASEURL }}" | sed -E 's|^https?://||g')
          echo "C8Y_DOMAIN=$C8Y_DOMAIN" >> .env
          echo 'C8Y_BASEURL="${{ secrets.C8Y_BASEURL }}"' >> .env
          echo 'C8Y_USER="${{ secrets.C8Y_USER }}"' >> .env
          echo 'C8Y_PASSWORD="${{ secrets.C8Y_PASSWORD }}"' >> .env
          cat .env

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: |
            tests/requirements.txt

      - uses: extractions/setup-just@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          just venv

      - name: Start demo
        run: |
          # just up-no-cache
          just IMAGE=${{matrix.job.target}} up

          if [ "${{matrix.job.bootstrap}}" = "true" ]; then
            just bootstrap --no-prompt
          fi

          # FIXME: Debug why the mapper does not start up cleanly sometimes
          # Is it just waiting for the token?
          #sleep 20
          #just shell systemctl restart tedge-mapper-c8y

      - name: Run tests
        run: just IMAGE=${{matrix.job.target}} test

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: reports-${{matrix.job.target}}
          path: output

      - name: Stop demo
        if: always()
        run: just IMAGE=${{matrix.job.target}} down-all

      - name: Install go-c8y-cli
        if: always()
        run: |
          mkdir -p "$HOME/.local/bin"
          curl -LSs https://github.com/reubenmiller/go-c8y-cli/releases/download/v2.22.4/c8y_linux_$(dpkg --print-architecture) -o "$HOME/.local/bin/c8y"
          chmod +x "$HOME/.local/bin/c8y"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Cleanup Devices
        if: always()
        run: |
          just cleanup "$DEVICE_ID"

      - name: Send report to commit
        uses: joonvena/robotframework-reporter-action@v2.2
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          report_path: 'output'
          show_passed_tests: 'false'
